add_newline = true
command_timeout = 1000
palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$c\
$cmake\
$dart\
$golang\
$java\
$lua\
$python\
$cmd_duration\
$jobs\
$status\
$line_break\
$character"""

[directory]
truncation_length = 8
read_only_style = '31'
read_only = ' '
repo_root_style = '39'
style = '74'
format = '[$read_only]($read_only_style)[$path]($style)'

[status]
disabled = false
style = '160'
symbol =  '✗ '
format = '[$symbol $status]($style)'

[character]
success_symbol = '[❯](76)'
error_symbol = '[❯](196)'
vimcmd_symbol = '[❮](76)'
vimcmd_visual_symbol = '[V](76)'


[fill]
symbol = ' '

[git_branch]
style = '76'
format = '[$symbol$branch]($style)'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = '214'
up_to_date = ''
untracked = ''
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
renamed = '襁 '
modified = ' !${count} '

[c]
format = '[ ](bold blue)'

[python]
symbol = ' '

[java]
symbol = ' '

[lua]
format = '[ ](blue)'

[dart]
symbol = ' '

[golang]
format = '[ ](bold cyan)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
