- name: Install yazi dependencies
  apt:
    name:
      - imagemagick
      - resvg
      - 7zip
      - poppler-utils
      - ffmpeg
    state: present
  become: true

- name: Install cargo tools
  community.general.cargo:
    name:
      - zoxide
      - yazi-build
  notify: install yazi packages
