- name: Install Go tools
  command: go install {{ item.url }}@latest
  args:
    creates: "{{ gopath }}/bin/{{ item.bin }}"
  loop:
    - { bin: "sesh", url: "github.com/joshmedeski/sesh/v2" }
    - { bin: "lazydocker", url: "github.com/jesseduffield/lazydocker" }
    - { bin: "pomo", url: "github.com/Bahaaio/pomo" }
    - { bin: "vhs", url: "github.com/charmbracelet/vhs" }
    - { bin: "goreleaser", url: "github.com/goreleaser/goreleaser" }
