- name: Install neovim build dependencies
  apt:
    name:
      - g++
      - curl
      - cmake
      - gettext
      - ninja-build
      - build-essential
    state: present
  become: true

- name: Clone neovim repository
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_env.HOME }}/github/neovim"
    version: master

- name: Build neovim
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/github/neovim"
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install neovim
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/github/neovim"
    target: install
  become: true
