- name: Install GNOME Desktop
  apt:
    name:
      - desktop-base
      - gnome-core
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-shell-extension-manager
    state: present
  become: true
