- name: Install i3 window manager and related packages
  apt:
    name:
      - i3-wm
      - xss-lock
      - polybar
      - picom
      - dunst
      - libnotify-bin
      - feh
      - flameshot
      - copyq
      - xclip
      - xinput
      - redshift-gtk
      - xsensors
      - network-manager
      - numlockx
      - gnome-calendar
      - gnome-weather
    state: present
  become: true

- name: Include betterlockscreen setup
  include_tasks: betterlockscreen.yml
