$pfp       = ~/Pictures/Personal/pfp.png
$font      = Inter Bold
$wallpaper = ~/Pictures/wallpapers/japan_lush_house.png

general {
    grace = 0
    no_fade_in = false
    ignore_empty_input = true
    disable_loading_bar = false
}

background {
    monitor =
    path = $wallpaper
    blur_passes = 3
    blur_size = 7
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 170, 45
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(100, 114, 125, 0.4)
    font_color = rgb(200, 200, 200)

    font_family = $font
    font_color = $font_color

    placeholder_text = Enter Password
    hide_input = false
    fade_on_empty = false

    position = 0, -425
}

# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  color = rgba(216, 222, 233, 0.70)
  font_size = 30
  font_family = $font

  position = 0, 410
  valign = center
  halign = center
}

# time
label {
  monitor =
  text = $TIME
  color = rgba(216, 222, 233, 0.70)
  font_size = 85
  font_family = $font
  position = 0, 310
}

# profile photo
image {
  monitor =
  path = $pfp
  border_size = 0
  size = 110
  position = 0, -265
}

# user
label {
  monitor =
  text = $USER
  color = rgba(216, 222, 233, 0.70)
  font_size = 16
  font_family = $font
  position = 0, -375
}
