- name: Install GUI apps from apt
  become: true
  vars:
    gui_packages:
      - vlc
      - mpv
      - wezterm
      - dbeaver-ce
      - nautilus
      - obs-studio
      - proton-vpn-gnome-desktop
  block:
    - name: Add WezTerm repository
      deb822_repository:
        name: wezterm
        uris: https://apt.fury.io/wez/
        suites: "*"
        components: "*"
        signed_by: https://apt.fury.io/wez/gpg.key
        state: present

    - name: Add DBeaver repository
      deb822_repository:
        name: dbeaver
        uris: https://dbeaver.io/debs/dbeaver-ce
        suites: /
        signed_by: https://dbeaver.io/debs/dbeaver.gpg.key
        state: present

    - name: Add Proton VPN repository
      deb822_repository:
        name: protonvpn-stable
        uris: https://repo.protonvpn.com/debian
        suites: stable
        components: main
        signed_by: https://repo.protonvpn.com/debian/public_key.asc
        state: present

    - name: Check ticktick installation
      stat:
        path: /usr/bin/ticktick
      register: ticktick_check

    - name: Install ticktick
      apt:
        deb: https://www.ticktick.com/static/getApp/download?type=linux_deb_x64
        state: present
      when: not ticktick_check.stat.exists

    - name: Install packages
      apt:
        name: "{{ gui_packages }}"
        state: present
        update_cache: true
