- name: Ensure GRUB_CMDLINE_LINUX_DEFAULT has required params
  vars:
    grub_params:
      - quiet
      - splash
  block:
    - name: Check if param exists
      lineinfile:
        path: /etc/default/grub
        regexp: '^\s*#?\s*GRUB_CMDLINE_LINUX_DEFAULT=".*\b{{ item }}\b'
        state: absent
      check_mode: true
      register: grub_check
      changed_when: false
      loop: "{{ grub_params }}"
      loop_control:
        label: "{{ item }}"

    - name: Insert missing params
      lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: '^\s*#?\s*(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
        line: '\1 {{ item.item }}"'
      when: item.found == 0
      loop: "{{ grub_check.results }}"
      loop_control:
        label: "{{ item.item }}"
      become: true
      notify: update grub

- name: Configure GRUB settings
  lineinfile:
    path: /etc/default/grub
    regexp: '^\s*#?\s*{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "GRUB_TIMEOUT", value: "0" }
    - { key: "GRUB_TIMEOUT_STYLE", value: "hidden" }
    - { key: "GRUB_TERMINAL", value: "console" }
  become: true
  notify: update grub
