- name: Include base installation
  import_tasks: base.yml

- name: Include plymouth installation
  import_tasks: plymouth.yml

- name: Include keyd installation
  import_tasks: keyd.yml

- name: Configure grub
  import_tasks: grub.yml

- name: Configure firewall
  import_tasks: ufw.yml
