- name: Install Bluetooth
  apt:
    name: bluetooth
    state: present
  become: true

- name: Install bluetui dependencies
  apt:
    name:
      - libdbus-1-dev
      - pkg-config
    state: present
  become: true

- name: Install bluetui
  community.general.cargo:
    name:
      - bluetui

- name: Enable Bluetooth service
  systemd:
    name: bluetooth
    enabled: true
    state: started
  become: true
