- name: Install network packages
  apt:
    name:
      - iwd
      - network-manager
    state: present
  become: true

- name: Uninstall wpa_supplicant
  apt:
    name: wpa_supplicant
    state: absent
  become: true

- name: Install impala
  community.general.cargo:
    name:
      - impala

- name: Configure NetworkManager to use iwd
  ini_file:
    path: /etc/NetworkManager/conf.d/iwd.conf
    section: device
    option: wifi.backend
    value: iwd
    no_extra_spaces: true
    mode: "0644"
  become: true
  notify: restart NetworkManager
