exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- hyprsunset
exec-once = uwsm-app -- dunst
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- copyq --start-server
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service

# applications
exec-once = [workspace 1 silent] uwsm-app -- zen
exec-once = [workspace 2 silent] uwsm-app -- wezterm start -e tmux new -A -s dev
exec-once = [workspace 5 silent] uwsm-app -- ticktick
exec-once = uwsm-app -- zapzap

# scratchpads
exec-once = uwsm-app -- wezterm start --class scratchpad -e tmux new -A -s scratch
exec-once = uwsm-app -- wezterm --config font_size=13 start --class btop -e btop
