# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    name = float-apps
    match:class = (localsend.*|.*copyq|.*pavucontrol|.*satty|xdg-desktop-portal-gtk|btop)

    float = true
    center = true
    size = 750 600
}

windowrule = size 900 580, match:class .*Nautilus
windowrule = size 900 600, match:class xdg-desktop-portal-gtk

windowrule {
  name = proton-pass
  match:title = Proton Pass

  float = true
  no_screen_share = true
  size = 881 680
}

windowrule = float on, match:class (org.gnome.Calculator|float)
windowrule = float on, match:class (xdg-desktop-portal-gtk|org.gnome.Nautilus)

windowrule = workspace 4, match:class Postman
windowrule = workspace 5, match:class ticktick
windowrule = workspace 9, match:class discord
windowrule = workspace 10, match:class .*zapzap

windowrule = no_screen_share on, match:class .*zapzap

# don't focus ticktick and discord when they open
windowrule = suppress_event activatefocus, match:class (ticktick|discord)

# scratchpads
windowrule {
    name = scratchpad
    match:class = scratchpad

    float = true
    size = 1100 800
    center = true
    workspace = special:scratchpad silent
}

windowrule {
    name = btop-scratchpad
    match:class = btop

    float = true
    size = 1261 823
    center = true
    workspace = special:btop silent
}

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
