- name: Install font dependencies
  apt:
    name:
      - unzip
      - fontconfig
    state: present
  become: true

- name: Check if JetBrains Mono Nerd Font is already installed
  stat:
    path: "{{ fonts_dir }}/JetBrainsMono"
  register: font_file

- name: Download and extract JetBrains Mono Nerd Font
  unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
    dest: "{{ fonts_dir }}/JetBrainsMono"
    remote_src: true
  when: not font_file.stat.exists

- name: Refresh font cache
  command: fc-cache -f
  changed_when: not font_file.stat.exists
  when: not font_file.stat.exists
