[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x6'\0\0\x3\xad\0\0\0\0\0\0\0\0\0\0\x6'\0\0\x3\xad\0\0\0\0\x2\0\0\0\x6@\0\0\0\0\0\0\0\0\0\0\x6'\0\0\x3\xad)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x6(\0\0\x3\xae\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=false
donation_message=true
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[performance]
cache_size_max=50

[system]
menubar=false
notificationCounter=false
quit_in_close=false
sidebar=false
spellCheckers=true
start_background=true
start_system=false
theme=light
tray_icon=false
tray_theme=symbolic_light
wayland=true

[web]
scroll_animator=true

[website]
open_page=false
